# set PATH so it includes user's private bin if it exists
if [ -d "$HOME/bin" ] ; then
    PATH="$HOME/bin:$PATH"
fi

for file in ~/.{aliases,dockerfunc}; do
    [[ -r "$file" ]] && [[ -f "$file" ]] && source "$file"
done

export DEBFULLNAME="Mark Adams"
export DEBEMAIL="mark@markadams.me"

export EDITOR=vim
export PROJECT_HOME=$HOME/Projects
export ATOM_REPOS_HOME=$PROJECT_HOME

# Enable virtualenvwrapper if installed
if [ -f "/usr/local/bin/virtualenvwrapper.sh" ]; then
    export WORKON_HOME=~/.venv
    source "/usr/local/bin/virtualenvwrapper.sh"
fi

# Mac-specific options
if [ `uname -s` == 'Darwin' ]; then
    PATH="/Users/madams/Library/Python/2.7/bin:$PATH"
fi

# Golang-specific things
export GOROOT=/usr/lib/go
export GOPATH=$PROJECT_HOME/go
export PATH=$PATH:$GOROOT/bin:$GOPATH/bin

# Node-specific things
export PATH="./node_modules/.bin:$PATH"

# Docker-specific things
if [ -z "$DOCKER_HOST" ] && type boot2docker > /dev/null 2>&1; then
    eval "$(boot2docker shellinit 2> /dev/null)"
fi

# Ruby-specific things
export PATH="$PATH:$HOME/.rvm/bin" # Add RVM to PATH for scripting
[[ -s "$HOME/.rvm/scripts/rvm" ]] && source "$HOME/.rvm/scripts/rvm" # Load RVM into a shell session *as a function*
